### ISSUE TITLE
Angular 11 - compatibility 

### ISSUE THREAD

**Issue by isayas** [talohana/angular-dark-mode#12]
npm ERR! Found: @angular/common@11.0.9
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~11.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/**common@"^10.1.4"** from angular-dark-mode@1.1.4
npm ERR! node_modules/angular-dark-mode
npm ERR!   **angular-dark-mode@"^1.1.4" from the root project**
npm ERR!

**Comment by talohana** [comment]
Thank you for pointing it out!
Would you like to submit a PR? If not I'll get to it in a day or two.
