### ISSUE TITLE
Not Installing on Angular 12.1.1

### ISSUE THREAD

**Issue by rahiyansafz** [talohana/angular-dark-mode#16]
### My Angular Version is:

Angular CLI: 12.1.1
Node: 14.17.2
Package Manager: npm 7.19.1
OS: linux x64

Angular: 12.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package Version:
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5

### **And tried to install the dark mode package, and it's throwing me an error**

![2021-07-08_11-01](https://user-images.githubusercontent.com/70625091/124865448-814c6a00-dfdc-11eb-81d1-62de8687781a.png)

**Comment by talohana** [comment]
Thank you for reporting!

It seems the package should be updated to support angular v12+

I will get to it later on today.

**Comment by rahiyansafz** [comment]
> Thank you for reporting!
> 
> It seems the package should be updated to support angular v12+
> 
> I will get to it later on today.

thanks! and keep making awesome packages!!!!! 

and i have a request to you! to make a package of progressive image loader like medium  :) it will be very helpful!
